// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/kontrolplane/feed/internal/store"

// AddFeedModal renders a native <dialog>. app.js calls showModal() on
// any <dialog class="modal"> htmx swaps into #modal, so the focus trap,
// Escape, the top layer, the backdrop and inert-ing the page behind all
// come from the platform rather than from the hand-rolled scrim this
// replaces.
//
// #probe-results starts out holding the form's own buttons, so probing
// swaps the "probe" action out and the "subscribe" action in — one
// place on screen for "what happens next".
func AddFeedModal(folders []store.Folder) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"add-feed-modal\" class=\"modal\" aria-labelledby=\"add-feed-title\"><header class=\"modal-head\"><span class=\"eyebrow\">subscribe / add feed</span><form method=\"dialog\" class=\"modal-close-form\"><button type=\"submit\" class=\"btn-icon\" aria-label=\"close\" data-close-modal><svg width=\"14\" height=\"14\" viewBox=\"0 0 14 14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M2 2 L12 12 M12 2 L2 12\"></path></svg></button></form></header><div class=\"modal-body scroll-y\"><h2 id=\"add-feed-title\" class=\"modal-title\">add a source.</h2><p class=\"pane-lead modal-lead\">the address of an rss or atom feed. a site url works too if you already know it carries one.</p><form class=\"modal-form\" hx-post=\"/feeds/probe\" hx-target=\"#probe-results\" hx-swap=\"innerHTML\" hx-indicator=\"#probe-indicator\" hx-disabled-elt=\"find button[type='submit']\"><div class=\"modal-field\"><label class=\"field-label\" for=\"add-feed-url\">source url</label> <input id=\"add-feed-url\" class=\"field no-lower\" type=\"url\" name=\"url\" inputmode=\"url\" autocomplete=\"off\" spellcheck=\"false\" placeholder=\"https://example.com/feed.xml\" required autofocus></div><div id=\"probe-results\"><div class=\"modal-actions\"><button type=\"button\" class=\"btn btn-ghost\" data-close-modal>cancel</button> <button type=\"submit\" class=\"btn btn-primary\">continue<span id=\"probe-indicator\" class=\"htmx-indicator probe-spinner\" aria-hidden=\"true\"></span></button></div></div></form></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ProbeResults is deliberately modest about what it claims. POST
// /feeds/probe (handler.go handleProbe) parses the form, reads "url",
// loads the folder list and renders — it makes no network request and
// parses no feed. The previous markup invented a "discovered feeds"
// table with one hardcoded row called "main feed" and a hardcoded
// status of "ok", which told the user their url had been validated when
// nothing had looked at it. What is actually true at this point is only
// that the url will be stored as a feed, so that is all this says.
func ProbeResults(url string, folders []store.Folder) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"probe-note\"><span class=\"eyebrow probe-note-label\">this url will be added as a feed</span> <span class=\"probe-note-url no-lower\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(url)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/addfeed.templ`, Line: 82, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span> <span class=\"probe-note-hint\">nothing has fetched it yet — it is read for the first time on the next refresh, and shows up empty until then.</span></div><input type=\"hidden\" name=\"feed_url\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(url)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/addfeed.templ`, Line: 89, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><div class=\"modal-field\"><label class=\"field-label\" for=\"subscribe-title\">name</label><input id=\"subscribe-title\" class=\"field no-lower\" type=\"text\" name=\"title\" placeholder=\"optional — defaults to the url\" autocomplete=\"off\"></div><div class=\"modal-field\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = FolderPicker(folders, "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><p class=\"modal-error\" role=\"alert\" data-modal-error hidden>could not subscribe. the server rejected the request.</p><div class=\"modal-actions modal-actions-ruled\"><button type=\"button\" class=\"btn btn-ghost\" data-close-modal>cancel</button><button type=\"button\" class=\"btn btn-primary\" hx-post=\"/feeds/subscribe\" hx-include=\"closest form\" hx-target=\"#sidebar\" hx-swap=\"outerHTML\" hx-disabled-elt=\"this\" hx-on::after-request=\"if(event.detail.successful){this.closest('dialog').close()}else{this.closest('form').querySelector('[data-modal-error]').hidden=false}\">subscribe <i class=\"arw\"></i></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
