// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// AddFolderModal renders a native <dialog>. app.js calls showModal() on
// any <dialog class="modal"> htmx swaps into #modal, so the focus trap,
// Escape, the top layer, the backdrop and inert-ing the page behind all
// come from the platform rather than from the hand-rolled scrim this
// replaces.
func AddFolderModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"add-folder-modal\" class=\"modal\" aria-labelledby=\"add-folder-title\"><header class=\"modal-head\"><span class=\"eyebrow\">new / folder</span><form method=\"dialog\" class=\"modal-close-form\"><button type=\"submit\" class=\"btn-icon\" aria-label=\"close\" data-close-modal><svg width=\"14\" height=\"14\" viewBox=\"0 0 14 14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M2 2 L12 12 M12 2 L2 12\"></path></svg></button></form></header><div class=\"modal-body scroll-y\"><h2 id=\"add-folder-title\" class=\"modal-title\">create a folder.</h2><p class=\"pane-lead modal-lead\">a group in the sidebar. every feed sits in exactly one.</p><form class=\"modal-form\" hx-post=\"/folders\" hx-target=\"#sidebar\" hx-swap=\"outerHTML\" hx-disabled-elt=\"find button[type='submit']\" hx-on::after-request=\"if(event.detail.successful){this.closest('dialog').close()}else{this.querySelector('[data-modal-error]').hidden=false}\"><div class=\"modal-field\"><label class=\"field-label\" for=\"add-folder-name\">folder name</label> <input id=\"add-folder-name\" class=\"field\" type=\"text\" name=\"name\" placeholder=\"e.g. tech, news, blogs\" autocomplete=\"off\" required autofocus></div><p class=\"modal-error\" role=\"alert\" data-modal-error hidden>could not create the folder. the server rejected the request.</p><div class=\"modal-actions\"><button type=\"button\" class=\"btn btn-ghost\" data-close-modal>cancel</button> <button type=\"submit\" class=\"btn btn-primary\">create <i class=\"arw\"></i></button></div></form></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
